kind: Service
apiVersion: v1
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  selector:
      matchLabels:
        app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
    spec:
      containers:
        - name: gateway
          image: gateway:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_PROFILES_ACTIVE
              value: docker