apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.16.2
        env:
          - name: cluster.name
            value: es01
          - name: node.name
            value: docker-cluster
          - name: discovery.seed_hosts
            value: "elasticsearch-second-chain"
          - name: cluster.initial_master_nodes
            value: es01,es02
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: http.cors.enabled
            value: 'true'
          - name: http.cors.allow-origin
            value: '*'
          - name: discovery.zen.minimum_master_nodes
            value: '2'
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: esdata1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch-second-chain
        image: elasticsearch:7.16.2
        env:
          - name: cluster.name
            value: es02
          - name: node.name
            value: docker-cluster
          - name: discovery.seed_hosts
            value: "elasticsearch"
          - name: cluster.initial_master_nodes
            value: es01,es02
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: http.cors.enabled
            value: 'true'
          - name: http.cors.allow-origin
            value: '*'
          - name: discovery.zen.minimum_master_nodes
            value: '2'
      - name: elastic-head
        image: mobz/elasticsearch-head:5
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: esdata2