apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: mongo-express
    tier: mongo-dashboard
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-express
    tier: mongo-dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo-express
    tier: mongo-dashboard
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
        tier: mongo-dashboard
    spec:
      containers:
      - name: mongo-express-eshop
        image: mongo-express:latest
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password