apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express-eshop
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    service: mongo-express
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo-express
      name: mongo-express-eshop
    spec:
      containers:
      - args:
        - mongodb
        - --smallfiles
        image: mongo-express:latest
        name: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: mongo-secret
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mongo-secret
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongo-eshop