kind: Service
apiVersion: v1
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 8091
    nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
      matchLabels:
        app: product-service
  replicas: 2
  template:
    metadata:
      labels:
        app: product-service
        tier: backend
    spec:
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8091
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: spring.data.mongodb.username
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mongo-secret
            - name: spring.data.mongodb.password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongo-secret